### ISSUE TITLE
A couple of enhancements in views and data model

### ISSUE THREAD

**Issue by funxies** [cuba-guides/cuba-petclinic-online-demo#1]
At your discretion:
1. Add the list of Pets on an Owner editor screen.
2. Add an Owner column on a Visits browser screen. Values in the Owner column could be links to the editor screen.
3. Link Veterinarians entity to Visits.

**Comment by mariodavid** [comment]
hi, thanks for the ideas.

What do you think - should that be part of the general petclinic application (https://github.com/cuba-platform/cuba-petclinic)? I assume that it would be benefitical to all examples. But what i'm not aware of if is, that we would then potentially have to update the screencasts... WDYT? (also @knstvk)

Bye
Mario

**Comment by funxies** [comment]
In my opinion, updating the online demo is just enough for now. Anyway, let's wait for @knstvk feedback.

**Comment by knstvk** [comment]
Hi
Items 1 and 2 are fine.
3 - perhaps a Visit should have a link to Veterinarian, but when you open a Veterinarian, the whole list of their visits is not needed.
Regarding where to add it - I think the online demo is enough.

**Comment by mariodavid** [comment]
done as part of Petclinic 2.x
